### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/Random-Item-Giver-Updater#1]
There's a lot to be done, before the software can fully release or even before the first public build.
Therefor, to have a structure and give all of you some kind of an idea of what I'm doing, I've created a roadmap of what is part of the development.
Please note that nothing on this list is guaranteed to make its way into the software, and there may also be things added to the software that are not on this list.

The following things will be completed before the first public beta build (in no particular order):
- [x] Make the top menu bar functional (Add all buttons, textblocks, etc.)
- [x] Add Arrow Symbols to the categories in the sidebar to better visualise whether they're collapsed or not
- [x] Make it, so you can click on the items in a loot table to edit their content. Add detection for when you load another loot table before saving the first one.
- [x] Add number to the items in a loot table to show their position (kind of a line number)
- [x] Add delete button to the items
- [x] Add option to add new items (similar to the old app, but in a wizard-like style)
- [x] Indicator next to the items that shows if they've been modified or deleted
- [x] Save button, that saves the changes and reloads the loot table
- [x] Have item editing, deleting and adding run asynchronously
- [x] Show progress bar when saving loot table
- [x] Add 'About' window and 'Changelog' window
- [x] Add warning that app is not affiliated with mojang studios in 'About' window
- [x] Show elapsed time in add item window
- [x] Fix major issues

**03.08.2023 - Public Beta was released!**

The following things will be added for a second beta build:
- [x] Item Remover (Similar to item adder, wizard like style, removes items from selected loot tables, shows where the items exist)
- [x] Duplicate finder (Lets you select if it should only search in current loot table or all loot tables, shows the duplicate items and where the exist, lets you remove them from all loot tables)
- [x] Fix laggy window resizing
- [x] Reload loot table after adding/
- [x] Fix insane memory consumption and memory not being freed up
- [x] Only show delete when hovering
- [x] Fix Item Remover not starting in the center of the screen
- [x] Fix Error message when trying to continue on page 3 of the Item Remover without any items being the default one
- [x] Fix duplicate text in group box header of Item Adding Wizard
- [x] Add button to remove items from the Item Remover
- [x] Fix "REPLACENBT" being added to all items
- [x] Fix error when closing Item Adding/Removing Wizard while no loot table is loaded
- [x] Fix "Added Items" textbox in Item Adding Wizard not being read-only
- [x] Fix item entrys in Item Adding
- [x] Fix items in "Random Amount Same Item" loot table not being detected correctly in duplicate finder.
- [x] Add scheme selection in loot table selector
- [x] Fix adding Items with NBT Tag not working at all
- [x] Fix items not being added to any loot tables when selecting "certain loot tables" without opening the selector
- [x] Add support for Item Remover in the Duplicate Finder
- [x] Fix several small issues regarding the Duplicate Finder
- [x] Fix typo in Item Adding window
- [x] Fix wrong error message when trying to continue without input in Item Remover
- [x] Fix loot tables being shown multiple times in selector when same item appears more than once
- [x] Fix items not being added/read correctly to/from the "Random Amount Same Item" Loot tables (variable changed!)

**24.02.2024 - Public Beta 2 was released!**

The following things will be added for thethird public beta:

- [x] Support for new Item Stack Components
- [x] Editor for NBT and Item Stack Components 
- [x] Add support for 1.21 folder structure

**27.08.2024 - Public Beta 3 was released!**

Things to do until Public Beta 4:

- [x] Complete massive rewrite
- [x] Fix fatal bugs (also visual)
- [x] Add support for new random item giver folder structure 

The following things will be done for the release:

- [ ] Proper handling of corrupted loot tables
- [ ] Replace all BackgroundWorkers with modern multithreading
- [ ] Potentially update WPF design to WinUI theme
- [ ] Fix crash when UPDATER.txt is not found
- [ ] Add icons to all windows
- [ ] View NBT/Component in duplicate finder
- [ ] Improve 'About' window to show third-party licenses in seperate window
- [ ] Update to .NET 10.0
- [ ] Fix remaining apparent issues
- [ ] #4 
- [ ] #5 
- [ ] #6 

The following things will be added in a later point in development and are not part of the first release:

- [ ] Item List Importer (Add option to import item list in item adding window)
- [ ] Settings menu (toggle log, edit quick access profiles with datapacks, edit schemes)
- [ ] Log/Console (Allows seeing past actions, with date/time, possibly allow dev commands)
- [ ] Profiles/Schemes (Profiles: Combination of datapack path, with option to also automatically load a loot table - Schemes: When adding items, select a scheme to automatically select loot tables that meet certain criteria, for example loot tables with a certain name or that contain certain words.)
- [ ] First Time Setup Screen (User files directory, appearance, default settings...)
- [ ] Custom Message Boxes (some can be hidden) => Will probably be implemented via SeeloewenLib
- [ ] "CTRL + F" Search option in main window to find items in loot tables
- [ ] Quick select option next to load button for data packs for loading profiles, as well as save button in that menu
- [ ] Duplicate detection when adding items (Shows warning, asks user whether to continue and ignore once, continue and ignore all or cancel)
- [ ] Add button click/hover animations and custom designs
- [ ] Check if the loot table is corrupted before loading/adding items to it
removing items
- [ ] Fix item name/nbt overlapping when being too long in most windows (possibly show ... at the cut off)
 over an item (this also means that modified indicator will need to be moved accordingly)
- [ ] Check if items are valid before adding them (both in main window when renaming and when using item adding wizard)
- [x] Fix high memory consummation when adding items caused by loot table objects
- [x] Support for 1.17

Please note: Support for the 1.17 Version of the Random Item Giver will be added after the full release of the software as it requires many adaptions to the software and would greatly increase the wait for the full release, even though it will be a rarely used feature.

**Comment by Seeloewen** [comment]
Moved some stuff to later development since I want to get the beta build some time soon.

**Comment by Seeloewen** [comment]
Public beta is out! Enjoy :)

**Comment by Seeloewen** [comment]
Came back to the project after a longer break. Rework of how large amounts of items are being displayed is finally done, fixing many performance issues.

**Comment by Seeloewen** [comment]
Another long break, but both the Duplicate Finder and Item Remover are now done!

**Comment by Seeloewen** [comment]
Decided to move support for 1.17 even further back in development priority, beyond 1.0. It would just take too much time right now and has pretty low priority.

**Comment by Seeloewen** [comment]
Decided what stuff will be in the next beta build and what will be moved further back! Mainly want to fix some apparent issues before getting the next version out.

**Comment by Seeloewen** [comment]
Second public beta is out! Next thing I'll focus on is working on new features.

**Comment by Seeloewen** [comment]
Next up is probably the settings window. I will try to add as much customizability as possible. When adding the settings there will be some settings that don't work, those are for future features.

Here's a list with some of my ideas:
```
# Settings

Appearance:
- Main Window Header Color
- Main Window Header Forecolor
- Main Window Sidebar Color
- Main Window Sidebar category forecolor
- Main Window Sidebar category color
- Main Window Workspace backcolor
- Main Window toggle big image in workspace
- Main Window item backcolor 1
- Main Window item backcolor 2
- Main Window item forecolor 1
- Main Window item forecolor 2
- Other Windows backcolor
- Other Windows forecolor
- Other Windows textbox color
- [Button to load default theme]

General:
- Language
- Automatically save open loot table when switching or closing
- Enable logging
- Automatically save logs
- logging type
- [Open logging directory]
- Enable Duplicate detection when adding items
- Skip loot table corruption check when adding items/loading loot tables etc. (not recommended) => show warning as it might cause corruption
- Skip item corruption check when adding items
- Import/Export Settings

Default settings:
- Load datapack by default
- Load loot table by default
- Enable checks for prefixes when adding/removing items by default
- Only search for absolute matches when using CTRL + F
```

**Comment by Seeloewen** [comment]
The new Item Stack Components system that replaced NBT in Snapshot 24w09a obviously completely screwed up most of the software, at least everything that worked directly in the files. Will make changes to adapt to this soon after I figured out what is broken. I'm probably gonna release a public Beta 2.1 to make the software usable again. I'm also gonna implement an Item Stack component editor at some point, but that's not gonna be in the next public beta.
